#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.12
# from Racc grammer file "".
#

require 'racc/parser.rb'

# parser classes
require 'regtest/front/bracket-scanner'  # scanner class (for splitting the string)
require 'regtest/front/letter'           # parser class for a letter
require 'regtest/front/range'            # parser class for a range of letters
require 'regtest/front/char-class'       # parser class for a char-class element
require 'regtest/front/bracket'          # parser class for a bracket

class RegtestFrontBracketParser < Racc::Parser

module_eval(<<'...end bracket-parser.y/module_eval...', 'bracket-parser.y', 63)
# modules for sharing procedures with main (regex) parser
include Regtest::Front::Range
include Regtest::Front::Letter
include Regtest::Front::CharClass
include Regtest::Front::Bracket

# execute to parse
def parse(value, options)
  @bracket_str = value[0]
  @options = options

  # check / verify input string
  if(!md = @bracket_str.match(/^(\[\^?)(.*)\]$/))
    raise "Internal error. bracket notation error"
  end
  bracket_header = md[1]
  seq_str = md[2]
    
  # scanning for spliting into elements
  scanner = Regtest::Front::BracketScanner.new(options)
  @q = scanner.scan(seq_str)
  
  # execute to parse
  begin
    parse_result = do_parse
  rescue Racc::ParseError => ex
    raise "Bracket " + ex.message
  end
  
  
  # return an analized bracket to main routine
  Bracket.new(value, parse_result)
end

# parse next token
def next_token
  @q.shift
end

# error handling routine
#def on_error(t, val, vstack)
  ## warn "t=#{t}, val=#{val}, vstack=#{vstack}"
  #raise "Bracket Parse error. str=#{@bracket_str} offset=#{val[1]}, letter=#{val[0]}, stack=#{vstack}"
#end
...end bracket-parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    11,     7,    25,     8,     9,    10,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    11,     7,    28,     8,
     9,    10,    12,    13,    14,    15,    16,    17,    18,    19,
    20,    21,    11,     7,   nil,     8,     9,    10,    12,    13,
    14,    15,    16,    17,    18,    19,    20,    21,    11,     7,
   nil,     8,     9,    10,    12,    13,    14,    15,    16,    17,
    18,    19,    20,    21,    11,     7,   nil,     8,     9,    10,
    12,    13,    14,    15,    16,    17,    18,    19,    20,    21,
    11,     7,   nil,     8,     9,    10,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    11,    22,   nil,    23,
     9,    10,    12,    13,    14,    15,    16,    23,    23,   nil,
    31,    32 ]

racc_action_check = [
     0,     0,     4,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,    23,    23,    22,    23,
    23,    23,    23,    23,    23,    23,    23,    23,    23,    23,
    23,    23,     2,     2,   nil,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     8,     8,
   nil,     8,     8,     8,     8,     8,     8,     8,     8,     8,
     8,     8,     8,     8,     7,     7,   nil,     7,     7,     7,
     7,     7,     7,     7,     7,     7,     7,     7,     7,     7,
    29,    29,   nil,    29,    29,    29,    29,    29,    29,    29,
    29,    29,    29,    29,    29,    29,    25,     1,   nil,     1,
    25,    25,    25,    25,    25,    25,    25,    26,    27,   nil,
    26,    27 ]

racc_action_pointer = [
    -3,    97,    29,   nil,    -1,   nil,   nil,    61,    45,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    18,    13,   nil,    93,   105,   106,   nil,    77,
   nil,   nil,   nil ]

racc_action_default = [
   -24,   -24,    -1,    -3,    -6,    -7,    -8,   -24,   -24,   -11,
   -12,   -13,   -14,   -15,   -16,   -17,   -18,   -19,   -20,   -21,
   -22,   -23,   -24,   -24,    -4,   -24,   -24,   -24,    33,    -2,
    -5,    -9,   -10 ]

racc_goto_table = [
    24,     1,    29,    30,   nil,   nil,   nil,   nil,    26,    27,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    24 ]

racc_goto_check = [
     3,     1,     2,     4,   nil,   nil,   nil,   nil,     1,     1,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,     3 ]

racc_goto_pointer = [
   nil,     1,   -21,    -2,   -22,   nil,   nil ]

racc_goto_default = [
   nil,   nil,     2,     3,     4,     5,     6 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 20, :_reduce_1,
  3, 20, :_reduce_2,
  1, 21, :_reduce_3,
  2, 21, :_reduce_4,
  3, 22, :_reduce_5,
  1, 22, :_reduce_6,
  1, 22, :_reduce_7,
  1, 22, :_reduce_8,
  3, 25, :_reduce_9,
  3, 25, :_reduce_10,
  1, 23, :_reduce_11,
  1, 23, :_reduce_12,
  1, 23, :_reduce_13,
  1, 23, :_reduce_14,
  1, 23, :_reduce_15,
  1, 23, :_reduce_16,
  1, 23, :_reduce_17,
  1, 23, :_reduce_18,
  1, 24, :_reduce_19,
  1, 24, :_reduce_20,
  1, 24, :_reduce_21,
  1, 24, :_reduce_22,
  1, 24, :_reduce_23 ]

racc_reduce_n = 24

racc_shift_n = 33

racc_token_table = {
  false => 0,
  :error => 1,
  :LEX_AND_AND => 2,
  :LEX_MINUS => 3,
  :LEX_BRACKET_START => 4,
  :LEX_BRACKET_END => 5,
  :LEX_BRACKET_START2 => 6,
  :LEX_CHAR => 7,
  :LEX_SIMPLE_ESCAPE => 8,
  :LEX_CODE_LITERAL => 9,
  :LEX_CONTROL_LETTER => 10,
  :LEX_META_LETTER => 11,
  :LEX_ESCAPED_LETTER => 12,
  :LEX_UNICODE => 13,
  :LEX_POSIX_CHAR_CLASS => 14,
  :LEX_SIMPLIFIED_CLASS => 15,
  :LEX_UNICODE_CLASS => 16,
  :LEX_SPECIAL_LETTER => 17,
  :LEX_SPACE => 18 }

racc_nt_base = 19

racc_use_result_var = false

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "LEX_AND_AND",
  "LEX_MINUS",
  "LEX_BRACKET_START",
  "LEX_BRACKET_END",
  "LEX_BRACKET_START2",
  "LEX_CHAR",
  "LEX_SIMPLE_ESCAPE",
  "LEX_CODE_LITERAL",
  "LEX_CONTROL_LETTER",
  "LEX_META_LETTER",
  "LEX_ESCAPED_LETTER",
  "LEX_UNICODE",
  "LEX_POSIX_CHAR_CLASS",
  "LEX_SIMPLIFIED_CLASS",
  "LEX_UNICODE_CLASS",
  "LEX_SPECIAL_LETTER",
  "LEX_SPACE",
  "$start",
  "brc_sq1",
  "brc_sq2",
  "brc_elm",
  "brc_lt1",
  "brc_lt2",
  "reg_bracket" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'bracket-parser.y', 8)
  def _reduce_1(val, _values)
    val[0]
  end
.,.,

module_eval(<<'.,.,', 'bracket-parser.y', 10)
  def _reduce_2(val, _values)
    val[0].and(val[2])
  end
.,.,

module_eval(<<'.,.,', 'bracket-parser.y', 14)
  def _reduce_3(val, _values)
    CharClass.new(val[0])
  end
.,.,

module_eval(<<'.,.,', 'bracket-parser.y', 16)
  def _reduce_4(val, _values)
    val[0].add(val[1])
  end
.,.,

module_eval(<<'.,.,', 'bracket-parser.y', 20)
  def _reduce_5(val, _values)
    TRange.new(val[0], val[2])
  end
.,.,

module_eval(<<'.,.,', 'bracket-parser.y', 22)
  def _reduce_6(val, _values)
    val[0]
  end
.,.,

module_eval(<<'.,.,', 'bracket-parser.y', 24)
  def _reduce_7(val, _values)
    val[0]
  end
.,.,

module_eval(<<'.,.,', 'bracket-parser.y', 26)
  def _reduce_8(val, _values)
    val[0]
  end
.,.,

module_eval(<<'.,.,', 'bracket-parser.y', 30)
  def _reduce_9(val, _values)
    Bracket.new(val[0], val[1])
  end
.,.,

module_eval(<<'.,.,', 'bracket-parser.y', 32)
  def _reduce_10(val, _values)
    Bracket.new(val[0], val[1])
  end
.,.,

module_eval(<<'.,.,', 'bracket-parser.y', 35)
  def _reduce_11(val, _values)
    TLetter.new(:LEX_CHAR,           val[0])
  end
.,.,

module_eval(<<'.,.,', 'bracket-parser.y', 36)
  def _reduce_12(val, _values)
    TLetter.new(:LEX_CHAR,           val[0][1..1])
  end
.,.,

module_eval(<<'.,.,', 'bracket-parser.y', 37)
  def _reduce_13(val, _values)
    TLetter.new(:LEX_CHAR,           val[0])
  end
.,.,

module_eval(<<'.,.,', 'bracket-parser.y', 38)
  def _reduce_14(val, _values)
    TLetter.new(:LEX_CODE_LITERAL,   val[0])
  end
.,.,

module_eval(<<'.,.,', 'bracket-parser.y', 39)
  def _reduce_15(val, _values)
    TLetter.new(:LEX_CONTROL_LETTER, val[0])
  end
.,.,

module_eval(<<'.,.,', 'bracket-parser.y', 40)
  def _reduce_16(val, _values)
    TLetter.new(:LEX_CONTROL_LETTER, val[0])
  end
.,.,

module_eval(<<'.,.,', 'bracket-parser.y', 41)
  def _reduce_17(val, _values)
    TLetter.new(:LEX_ESCAPED_LETTER, val[0])
  end
.,.,

module_eval(<<'.,.,', 'bracket-parser.y', 42)
  def _reduce_18(val, _values)
    TLetter.new(:LEX_UNICODE,        val[0])
  end
.,.,

module_eval(<<'.,.,', 'bracket-parser.y', 45)
  def _reduce_19(val, _values)
    TLetter.new(:LEX_POSIX_CHAR_CLASS, val[0])
  end
.,.,

module_eval(<<'.,.,', 'bracket-parser.y', 46)
  def _reduce_20(val, _values)
    TLetter.new(:LEX_SIMPLIFIED_CLASS, val[0])
  end
.,.,

module_eval(<<'.,.,', 'bracket-parser.y', 47)
  def _reduce_21(val, _values)
    TLetter.new(:LEX_UNICODE_CLASS,  val[0])
  end
.,.,

module_eval(<<'.,.,', 'bracket-parser.y', 48)
  def _reduce_22(val, _values)
    TLetter.new(:LEX_SPECIAL_LETTER, val[0])
  end
.,.,

module_eval(<<'.,.,', 'bracket-parser.y', 49)
  def _reduce_23(val, _values)
    TLetter.new(:LEX_SPACE,          val[0])
  end
.,.,

def _reduce_none(val, _values)
  val[0]
end

end   # class RegtestFrontBracketParser
